// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.1
// source: task.proto

package task

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_RUNNING   TaskStatus = 0
	TaskStatus_TASK_STATUS_SUCCEEDED TaskStatus = 1
	TaskStatus_TASK_STATUS_CANCELLED TaskStatus = 2
	TaskStatus_TASK_STATUS_FAILED    TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_RUNNING",
		1: "TASK_STATUS_SUCCEEDED",
		2: "TASK_STATUS_CANCELLED",
		3: "TASK_STATUS_FAILED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_RUNNING":   0,
		"TASK_STATUS_SUCCEEDED": 1,
		"TASK_STATUS_CANCELLED": 2,
		"TASK_STATUS_FAILED":    3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       string                 `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Pid           int64                  `protobuf:"varint,4,opt,name=pid,proto3" json:"pid,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=task.TaskStatus" json:"status,omitempty"`
	ExecutedAt    int64                  `protobuf:"varint,6,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	MemUsage      uint64                 `protobuf:"varint,7,opt,name=mem_usage,json=memUsage,proto3" json:"mem_usage,omitempty"`
	NumThreads    uint32                 `protobuf:"varint,8,opt,name=num_threads,json=numThreads,proto3" json:"num_threads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Task) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Task) GetPid() int64 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_RUNNING
}

func (x *Task) GetExecutedAt() int64 {
	if x != nil {
		return x.ExecutedAt
	}
	return 0
}

func (x *Task) GetMemUsage() uint64 {
	if x != nil {
		return x.MemUsage
	}
	return 0
}

func (x *Task) GetNumThreads() uint32 {
	if x != nil {
		return x.NumThreads
	}
	return 0
}

type InvokeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	WorkingDir    string                 `protobuf:"bytes,4,opt,name=working_dir,json=workingDir,proto3" json:"working_dir,omitempty"`
	EnvVars       map[string]string      `protobuf:"bytes,5,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTaskRequest) Reset() {
	*x = InvokeTaskRequest{}
	mi := &file_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTaskRequest) ProtoMessage() {}

func (x *InvokeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTaskRequest.ProtoReflect.Descriptor instead.
func (*InvokeTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeTaskRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InvokeTaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *InvokeTaskRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InvokeTaskRequest) GetWorkingDir() string {
	if x != nil {
		return x.WorkingDir
	}
	return ""
}

func (x *InvokeTaskRequest) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

type InvokeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeTaskResponse) Reset() {
	*x = InvokeTaskResponse{}
	mi := &file_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeTaskResponse) ProtoMessage() {}

func (x *InvokeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeTaskResponse.ProtoReflect.Descriptor instead.
func (*InvokeTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{3}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type StopTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskRequest) Reset() {
	*x = StopTaskRequest{}
	mi := &file_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskRequest) ProtoMessage() {}

func (x *StopTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskRequest.ProtoReflect.Descriptor instead.
func (*StopTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{4}
}

func (x *StopTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stopped       bool                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	Via           string                 `protobuf:"bytes,2,opt,name=via,proto3" json:"via,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopTaskResponse) Reset() {
	*x = StopTaskResponse{}
	mi := &file_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopTaskResponse) ProtoMessage() {}

func (x *StopTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopTaskResponse.ProtoReflect.Descriptor instead.
func (*StopTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{5}
}

func (x *StopTaskResponse) GetStopped() bool {
	if x != nil {
		return x.Stopped
	}
	return false
}

func (x *StopTaskResponse) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

func (x *StopTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type LogsTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsTaskRequest) Reset() {
	*x = LogsTaskRequest{}
	mi := &file_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsTaskRequest) ProtoMessage() {}

func (x *LogsTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsTaskRequest.ProtoReflect.Descriptor instead.
func (*LogsTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{6}
}

func (x *LogsTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LogsTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StdoutPath    string                 `protobuf:"bytes,1,opt,name=stdout_path,json=stdoutPath,proto3" json:"stdout_path,omitempty"`
	StderrPath    string                 `protobuf:"bytes,2,opt,name=stderr_path,json=stderrPath,proto3" json:"stderr_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogsTaskResponse) Reset() {
	*x = LogsTaskResponse{}
	mi := &file_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogsTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogsTaskResponse) ProtoMessage() {}

func (x *LogsTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogsTaskResponse.ProtoReflect.Descriptor instead.
func (*LogsTaskResponse) Descriptor() ([]byte, []int) {
	return file_task_proto_rawDescGZIP(), []int{7}
}

func (x *LogsTaskResponse) GetStdoutPath() string {
	if x != nil {
		return x.StdoutPath
	}
	return ""
}

func (x *LogsTaskResponse) GetStderrPath() string {
	if x != nil {
		return x.StderrPath
	}
	return ""
}

var File_task_proto protoreflect.FileDescriptor

const file_task_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"task.proto\x12\x04task\x1a\x1bgoogle/protobuf/empty.proto\"\xe3\x01\n" +
	"\x04Task\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x12\x10\n" +
	"\x03pid\x18\x04 \x01(\x03R\x03pid\x12(\n" +
	"\x06status\x18\x05 \x01(\x0e2\x10.task.TaskStatusR\x06status\x12\x1f\n" +
	"\vexecuted_at\x18\x06 \x01(\x03R\n" +
	"executedAt\x12\x1b\n" +
	"\tmem_usage\x18\a \x01(\x04R\bmemUsage\x12\x1f\n" +
	"\vnum_threads\x18\b \x01(\rR\n" +
	"numThreads\"\x81\x02\n" +
	"\x11InvokeTaskRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1f\n" +
	"\vworking_dir\x18\x04 \x01(\tR\n" +
	"workingDir\x12?\n" +
	"\benv_vars\x18\x05 \x03(\v2$.task.InvokeTaskRequest.EnvVarsEntryR\aenvVars\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05_name\"4\n" +
	"\x12InvokeTaskResponse\x12\x1e\n" +
	"\x04task\x18\x01 \x01(\v2\n" +
	".task.TaskR\x04task\"5\n" +
	"\x11ListTasksResponse\x12 \n" +
	"\x05tasks\x18\x01 \x03(\v2\n" +
	".task.TaskR\x05tasks\"%\n" +
	"\x0fStopTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"^\n" +
	"\x10StopTaskResponse\x12\x18\n" +
	"\astopped\x18\x01 \x01(\bR\astopped\x12\x10\n" +
	"\x03via\x18\x02 \x01(\tR\x03via\x12\x1e\n" +
	"\x04task\x18\x03 \x01(\v2\n" +
	".task.TaskR\x04task\"%\n" +
	"\x0fLogsTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"T\n" +
	"\x10LogsTaskResponse\x12\x1f\n" +
	"\vstdout_path\x18\x01 \x01(\tR\n" +
	"stdoutPath\x12\x1f\n" +
	"\vstderr_path\x18\x02 \x01(\tR\n" +
	"stderrPath*s\n" +
	"\n" +
	"TaskStatus\x12\x17\n" +
	"\x13TASK_STATUS_RUNNING\x10\x00\x12\x19\n" +
	"\x15TASK_STATUS_SUCCEEDED\x10\x01\x12\x19\n" +
	"\x15TASK_STATUS_CANCELLED\x10\x02\x12\x16\n" +
	"\x12TASK_STATUS_FAILED\x10\x032\x82\x02\n" +
	"\vTaskService\x12?\n" +
	"\n" +
	"InvokeTask\x12\x17.task.InvokeTaskRequest\x1a\x18.task.InvokeTaskResponse\x12<\n" +
	"\tListTasks\x12\x16.google.protobuf.Empty\x1a\x17.task.ListTasksResponse\x129\n" +
	"\bStopTask\x12\x15.task.StopTaskRequest\x1a\x16.task.StopTaskResponse\x129\n" +
	"\bLogsTask\x12\x15.task.LogsTaskRequest\x1a\x16.task.LogsTaskResponseB(Z&loadept.com/pkg/asyncker/internal/taskb\x06proto3"

var (
	file_task_proto_rawDescOnce sync.Once
	file_task_proto_rawDescData []byte
)

func file_task_proto_rawDescGZIP() []byte {
	file_task_proto_rawDescOnce.Do(func() {
		file_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)))
	})
	return file_task_proto_rawDescData
}

var file_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_task_proto_goTypes = []any{
	(TaskStatus)(0),            // 0: task.TaskStatus
	(*Task)(nil),               // 1: task.Task
	(*InvokeTaskRequest)(nil),  // 2: task.InvokeTaskRequest
	(*InvokeTaskResponse)(nil), // 3: task.InvokeTaskResponse
	(*ListTasksResponse)(nil),  // 4: task.ListTasksResponse
	(*StopTaskRequest)(nil),    // 5: task.StopTaskRequest
	(*StopTaskResponse)(nil),   // 6: task.StopTaskResponse
	(*LogsTaskRequest)(nil),    // 7: task.LogsTaskRequest
	(*LogsTaskResponse)(nil),   // 8: task.LogsTaskResponse
	nil,                        // 9: task.InvokeTaskRequest.EnvVarsEntry
	(*emptypb.Empty)(nil),      // 10: google.protobuf.Empty
}
var file_task_proto_depIdxs = []int32{
	0,  // 0: task.Task.status:type_name -> task.TaskStatus
	9,  // 1: task.InvokeTaskRequest.env_vars:type_name -> task.InvokeTaskRequest.EnvVarsEntry
	1,  // 2: task.InvokeTaskResponse.task:type_name -> task.Task
	1,  // 3: task.ListTasksResponse.tasks:type_name -> task.Task
	1,  // 4: task.StopTaskResponse.task:type_name -> task.Task
	2,  // 5: task.TaskService.InvokeTask:input_type -> task.InvokeTaskRequest
	10, // 6: task.TaskService.ListTasks:input_type -> google.protobuf.Empty
	5,  // 7: task.TaskService.StopTask:input_type -> task.StopTaskRequest
	7,  // 8: task.TaskService.LogsTask:input_type -> task.LogsTaskRequest
	3,  // 9: task.TaskService.InvokeTask:output_type -> task.InvokeTaskResponse
	4,  // 10: task.TaskService.ListTasks:output_type -> task.ListTasksResponse
	6,  // 11: task.TaskService.StopTask:output_type -> task.StopTaskResponse
	8,  // 12: task.TaskService.LogsTask:output_type -> task.LogsTaskResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_task_proto_init() }
func file_task_proto_init() {
	if File_task_proto != nil {
		return
	}
	file_task_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_proto_rawDesc), len(file_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_proto_goTypes,
		DependencyIndexes: file_task_proto_depIdxs,
		EnumInfos:         file_task_proto_enumTypes,
		MessageInfos:      file_task_proto_msgTypes,
	}.Build()
	File_task_proto = out.File
	file_task_proto_goTypes = nil
	file_task_proto_depIdxs = nil
}
