syntax = "proto3";

package task;

option go_package = "loadept.com/pkg/asyncker/internal/task";

import "google/protobuf/empty.proto";

enum TaskStatus {
    TASK_STATUS_RUNNING     = 0;
    TASK_STATUS_SUCCEEDED   = 1;
    TASK_STATUS_CANCELLED   = 2;
    TASK_STATUS_FAILED      = 3;
}

message Task {
    string name = 1;
    string command = 2;
    repeated string args = 3;
    int64 pid = 4;
    TaskStatus status = 5;
    int64 executed_at = 6;
    uint64 mem_usage = 7;
    uint32 num_threads = 8;
}

message InvokeTaskRequest {
    string command = 1;
    repeated string args = 2;
    optional string name = 3;
    string working_dir = 4;
    map<string, string> env_vars = 5;
}

message InvokeTaskResponse {
    Task task = 1;
}

message ListTasksResponse {
    repeated Task tasks = 1;
}

message StopTaskRequest {
  string name = 1;
}

message StopTaskResponse {
  bool stopped = 1;
  string via = 2;
  Task task = 3;
}

service TaskService {
    rpc InvokeTask (InvokeTaskRequest) returns (InvokeTaskResponse);
    rpc ListTasks (google.protobuf.Empty) returns (ListTasksResponse);
    rpc StopTask (StopTaskRequest) returns (StopTaskResponse);
}
