syntax = "proto3";

package task;

option go_package = "loadept.com/pkg/asyncker/internal/task";

import "google/protobuf/empty.proto";

enum TaskStatus {
    TASK_STATUS_RUNNING     = 0;
    TASK_STATUS_SUCCEEDED   = 1;
    TASK_STATUS_FAILED      = 2;
}

message Task {
    string name = 2;
    string command = 3;
    repeated string args = 4;
    int64 pid = 5;
    TaskStatus status = 6;
    int64 executed_at = 7;
}

message InvokeTaskRequest {
    string command = 1;
    repeated string args = 2;
    optional string name = 3;
}

message InvokeTaskResponse {
    Task task = 1;
}

message ListTasksResponse {
    repeated Task tasks = 1;
}

service TaskService {
    rpc InvokeTask (InvokeTaskRequest) returns (InvokeTaskResponse);
    rpc ListTasks (google.protobuf.Empty) returns (ListTasksResponse);
}
